$(document).ready(function(){
    $("#hide").click(function(){
        $(".vote").hide();
    });
    $("#show").click(function(){
        $(".vote").show();
    });
    $("#hoverbox").hover(function(){
        $("#hoverbox").fadeOut(1000);
});
   $("#hoverbox").hover(function(){
     $(".appear").fadeIn(1000);
});
